### ISSUE TITLE
README instructions don't appear to work

### ISSUE THREAD

**Issue by raghavsethi** [livekit/client-sdk-react-native-expo-plugin#2]
Hey folks, I'm trying to add LiveKit to my Expo RN project and based on the documentation [here](https://github.com/livekit/client-sdk-react-native), it looks like I should only have to follow the README for this repository.

However, in an otherwise working Expo app, if I do the following:
```
npx expo install @livekit/react-native @livekit/react-native-expo-plugin
```

and then add `@livekit/react-native-expo-plugin` to the list of plugins in `app.config.js`, I get the following error during `npx expo prebuild --clean`

```
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to find a specification for `livekit-react-native-webrtc` depended upon by `livekit-react-native`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Since the README also suggests installing [@config-plugins/react-native-webrtc](https://www.npmjs.com/package/@config-plugins/react-native-webrtc), I did so:

```
npx expo install react-native-webrtc @config-plugins/react-native-webrtc
```

On `npx expo prebuild --clean`, this produces:
```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to find a specification for `livekit-react-native-webrtc` depended upon by `livekit-react-native`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 ```
 
After adding `@config-plugins/react-native-webrtc` to plugins in `app.config.js`,  and re-running  `npx expo prebuild --clean` I still get the same error.

Could you clarify whether `@config-plugins/react-native-webrtc` is just 'highly suggested' or required to work? 

## Update

Submitted a [PR](https://github.com/livekit/client-sdk-react-native-expo-plugin/pull/3) to fix the README

**Comment by davidliu** [comment]
Thanks for the PR!
